### ISSUE TITLE
Email login

### ISSUE THREAD

**Issue by ZaninAndrea** [IglooCloud/IglooBering#100]
Implement a `sendLoginEmail` mutation which sends an email containing a link that logs you in

Implementation steps:
- add the mutation to the schema
- the handler should send an email containing the link

**Comment by ZaninAndrea** [comment]
@SamueleDassatti what about the `createToken` mutation? Should we send an email every time the user wants to create a special token?

**Comment by SamueleDassatti** [comment]
I believe we should
