### ISSUE TITLE
unclaimedDevice/unclaimedValue query

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#110]
**Is your feature request related to a problem? Please describe.**
Aurora should be able to know whether the id contained in a device QR code is associated with an existing unclaimedDevice.

**Describe the solution you'd like**
Add an `unclaimedDevice` and an `unclaimedValue` query.

**Comment by ZaninAndrea** [comment]
use
```
{
   device(id:"id"){
       environment{
          id
       }
   }
}
```

and check whether `environment` is null
