### ISSUE TITLE
Account verification email does not work

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#117]
**Current Behaviour**
The link in the account verification email redirects to a page that says "Auser with this email already exists".

**Comment by ZaninAndrea** [comment]
What do you mean by password verification email?

**Comment by SamueleDassatti** [comment]
I was talking about the account verification email.

**Comment by ZaninAndrea** [comment]
closed by 01560dbd80517f2ef981bc84aa2919a34f712849
