### ISSUE TITLE
resendVerificationEmail should not require authentication

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#126]
**Is your feature request related to a problem? Please describe.**
Aurora can't allow users to resend themselves a verification email in case they lost it due the resendVerificationEmail mutation requiring the user to be authenticated

**Describe the solution you'd like**
The resendVerificationEmail shouldn't require authentication.

**Comment by ZaninAndrea** [comment]
@SamueleDassatti resendVerificationEmail is now unauthenticated and accepts an email parameter
