### ISSUE TITLE
createToken should support emailCertificate

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#133]
**Is your feature request related to a problem? Please describe.**
The `createToken` mutation is currently unavailable to email-only users since it requires a `passwordCertificate`, `webAuthnCertificate` or `totpCertificate`.

**Describe the solution you'd like**
Should email-only users be required to receive a log in link every time they want to create a token or should mutations that require a special token just work for email-only users?

@ZaninAndrea

**Comment by ZaninAndrea** [comment]
An authenticated `sendConfimationEmail(operation:Operation!)` sends a confirmation email to the user, a link in the confirmation email redirects to Aurora with a one-time token put in a query parameter (logInToken, deleteUserToken, ...) 

`createToken` accepts emailCertificate

**Comment by ZaninAndrea** [comment]
Email-only login now requires to use the `sendConfirmationEmail(email:"---@---.---", operation:LOG_IN)` mutation, the link in the email will redirect to Aurora as before, but the token passed to Aurora now has to be converted to a certificate using the `verifyEmailToken(token:"---")` mutation, the certificate obtained can be used in the `logIn` mutation.

Similar process can be used to create a token.

@SamueleDassatti
