### ISSUE TITLE
Fetch devices created from producer account

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#141]
**Is your feature request related to a problem? Please describe.**
Aurora can't show a list of all unclaimed devices.

**Describe the solution you'd like**
Add a query to fetch all devices that haven't been added to an environment.

**Comment by ZaninAndrea** [comment]
That's not how unclaimed devices should be used: unclaimed devices are linked only to the producer so a user cannot know which devices he did not claim.

If you wanted to show the unclaimed devices in Aurora from the producer account I think you shouldn't as Aurora is meant for the end user. At some point we will need to develop a producer dashboard though.
@SamueleDassatti

**Comment by SamueleDassatti** [comment]
@ZaninAndrea The list of unclaimed devices isn't meant for users, but rather for developers that want to create values for unclaimed devices from Aurora and, as you said, it would be useful for a future dev-only app.

That said, I think that, if we wanted to introduce an Igloo Partner Dashboard down the line, it would make sense to remove some developer options from Aurora, such as the "Create device/value" dialogs, what do you think?

**Comment by ZaninAndrea** [comment]
I would structure it like this: `user.devicesCreated` (naming open for new ideas) which returns all the created devices claimed or unclaimed, but allows you to pass a filter to select only the unclaimed ones or viceversa

**Comment by SamueleDassatti** [comment]
I agree, as for the naming I'd go with `user.developerDevices` while we look for a better name.
