### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by ZaninAndrea** [IglooCloud/IglooBering#149]
PermanentTokens should become services and be billed separately (similarly to devices)

**Comment by ZaninAndrea** [comment]
@SamueleDassatti I think that PermanentTokens have a different purpose from services: they allow the developer to easily authenticate to its account without having to refresh the token, they are a tool particularly useful in development.
Services instead are conceptually distinct from the producer, they will be the backbone of the Github Apps like platform for data processing and alerts.

**Comment by SamueleDassatti** [comment]
That makes sense. Because of this I think we should also remove the options to manage permanent tokens in Aurora as they would become a developer-only options.

**Comment by ZaninAndrea** [comment]
Can you leave them as a developer option? At the moment it's quite complex obtaining a temporary or permanent token through the api, so being able to easily generate a permanent tokens speeds up a lot the development

**Comment by SamueleDassatti** [comment]
Okay
