### ISSUE TITLE
Add queries for device types and firmwares

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#157]
**Is your feature request related to a problem? Please describe.**
Aurora needs a list of all the device types and firmwares of the user devices in order to display deviceType/firmware couples as filters even if none of the devices with that couple has been loaded.

**Describe the solution you'd like**
Add a query for device types and for firmware.

```
{
  user {
    uniqueDeviceTypes
    uniqueFirmwares
  }
}
```
or 
```
{
  user {
    uniqueDeviceTypes {
      name
      count
      uniqueFirmwares {
        name
        count
     }
  }
}
```

I personally prefer the second syntax as it would easier to implement in Aurora. @ZaninAndrea what do you think?

**Comment by ZaninAndrea** [comment]
The latter format seems cleaner, but I think it would conflict with Apollo merge algorithm as for the settings, with the difference that I can't assign a different ID to each uniqueDeviceType object

**Comment by SamueleDassatti** [comment]
Yeah, it would almost certainly make Apollo crash, so we should choose for the former.

**Comment by ZaninAndrea** [comment]
The former does not associate firmware and deviceType, I'd go for a single field `uniqueFirmwares:[[String!]!]!` that returns an array of pairs deviceType and firmware, this should be fairly easy to parse and shouldn't conflict with Apollo

**Comment by SamueleDassatti** [comment]
👍
