### ISSUE TITLE
Internal server error when trying to delete a floatSeriesValue with at least one node

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#166]
**Current Behaviour**
Bering returns an internal server error when trying to delete a floatSeriesValue that has at least one node.

**Comment by ZaninAndrea** [comment]
@SamueleDassatti cannot reproduce, can you check whether the bug is still there

**Comment by SamueleDassatti** [comment]
The bug appears to be gone, I'm closing the issue
