### ISSUE TITLE
Fix environmentStoppedSharingWithUser subscription

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#208]
The `environmentStoppedSharingWithUser` subscription returns all fields if just `id` is requested and throws an internal server error (code: `fd3f113e-f7cb-4d7e-b763-0d30821e1771`) if other fields are requested.

```
// returns all fields
subscription{
  environmentStoppedSharingWithUser{
    user{
      id
    }
  }
}

// returns all fields and throws an internal server error
subscription{
  environmentStoppedSharingWithUser{
    user{
      id
      name
    }
  }
}
```

**Comment by ZaninAndrea** [comment]
closed by ebeca0b932baa7f108c8c5458f6371c81ac5716d
