### ISSUE TITLE
uniqueFirmwares should be an object

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#227]
The `uniqueFirmwares` field should be an object with device types as keys and arrays of firmwares as values, this way creating a deviceType/firmware list would require less client-side work for developers.

Example:
```
uniqueFirmwares: {
   Thermometer: [v0.1, v0.2, v1.0],
   Sprinkler: [v0, v2]
}
```

**Comment by ZaninAndrea** [comment]
The GraphQL syntax does not allow us to return an object with keys that depend on the database. We could return the object as a JSON string, but that's inconsistent with GraphQL.

I'd stick with the current syntax as parsing it to an object is pretty low effort.
