### ISSUE TITLE
Internal server error when creating category series node

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#242]
The `createCategorySeriesNode` mutation returns an internal server error.

### Mutation
```
mutation {
  createCategorySeriesNode(seriesId:"a81b0d27-53b0-4824-8f10-a9cae3af2156", value:"a") {
    id
  }
}
```

### Error code
68d95aa7-4eb0-46e9-8967-6bd6f70fcee7

**Comment by ZaninAndrea** [comment]
Fixed deploying the last development build
