### ISSUE TITLE
Users should not be able to invite unverified users to an environment

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#256]
Currently, an environment can be shared with an unverified user, but they cannot accept it. We should instead block users from sharing environments with unverified users and remove the ""Unverified users can not accept environment share"" error.

**Comment by ZaninAndrea** [comment]
I don't thing this is a good way of handling the issue, it's reasonable to invite an unverified user in an environment, we should simply disable the accept button for the receiver user.
