### ISSUE TITLE
Different verification email for WebAuthn users

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#262]
**Is your feature request related to a problem? Please describe.**
Aurora does not know whether a user signing in with a verification email did so after being prompted to verify their email before registering a WebAuthn factor. Because of this, it is impossible to set up WebAuthn at sign up.

**Describe the solution you'd like**
WebAuthn users should receive a different verification email whose link to aurora includes a query parameter such as `?from=webauthn`. This email should be sent with a dedicated mutation.

**Comment by ZaninAndrea** [comment]
Use the mutation `sendConfirmationEmail(email: "...", operation: LOG_IN_FROM_WEBAUTHN)`
