### ISSUE TITLE
Block future notification dates

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#267]
The notification `date` field should not be settable to a future date.

**Original**
If the `date` field of a notification is set to a future date, the push notification should be scheduled for that date and it should not be visible among the device notifications.

**Comment by ZaninAndrea** [comment]
This is a very hard thing to do, we cannot rely on `setTimeout` or the likes because of their inaccuracy and because they would clog the node loop in the server. We would need to setup some kind of scheduling system to manage this.

I'd rather disallow setting date to a date in the future.

**Comment by SamueleDassatti** [comment]
Ok, changing the issue to "Block future notification dates".
