### ISSUE TITLE
Variable hidden filter error

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#272]
Bering returns an internal server error when an `hidden` filter is applied to `variables` or `variableCount`.

### Query
```
{
  thing(id: "9e4b3f6f-c592-42af-9d29-95e34dd0c46a") {
    id
    variableCount(filter: {hidden: false})
    variables(limit: 20, offset: 0, filter: {hidden: false}) {
      id
    }
  }
}
```

### Error codes
 **- variableCount:** da2bf0b8-8834-4e57-b23a-04a400da055c
 **- variables:** 4187b9a2-b11f-45d3-9271-6b938445796c

**Comment by ZaninAndrea** [comment]
block hidden filter for non environment authorized users
