### ISSUE TITLE
enableWebAuthn should require special token

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#85]
**Describe the solution you'd like**
The enableWebAuthn mutation should require a special token, like changePassword.

```
//get token
mutation {
  createToken(tokenType: ENABLE_WEB_AUTHN, password: ...)
}

//enable WebAuthn
mutation {
	enableWebauthn(challengeResponse: ..., jwtChallenge: ...)
}
```

**Comment by SamueleDassatti** [comment]
Would it be better for enableWebAuthn and changePassword to require the same token type?

**Comment by ZaninAndrea** [comment]
useremo un nuovo token CHANGE_AUTHENTICATION che permette di abilitare/disabilitare/cambiare password e webauthn factors
