### ISSUE TITLE
Remove email argument from getWebAuthnEnableChallenge

### ISSUE THREAD

**Issue by SamueleDassatti** [IglooCloud/IglooBering#97]
**Is your feature request related to a problem? Please describe.**
`getWebAuthnEnableChallenge` requires email as an argument even though it can only be authorized by a personal token, thus being able to access the user email.

**Describe the solution you'd like**
`getWebAuthnEnableChallenge` should not require any argument.

```
getWebAuthnEnableChallenge {
    publicKeyOptions
    jwtChallenge
}
```

**Comment by ZaninAndrea** [comment]
Steps to implement:
* remove email from `getWebAuthnEnableChallenge` parameters
* load the email from the user in the query handler
